

function crearGaleria () {
  
  
galeria = [
  {texto: 'La Anástrofe de Nuestra Señora del Futuro', imagen:comunismosolar, tecla: 'Apreta "A" para empezar', tamanoTexto:40, posicionXtexto: 150, posicionYtexto: 100, posicionXimagen: 510, posicionYimagen: 800, escala: 0.70, opacidad:255, anchoTexto: 400},
  {texto: 'No me mostraron exactamente cuándo, ni a que Humanidad le correspondería tal destino, pero la visión empezó como cualquier otro apocalipsis: con fuego lloviendo desde el cielo. Las naciones e imperios de la Tierra habían decidido, por fin, saltar la fina línea que los había excluido durante milenios del catálogo de las extinciones terráqueas. Las causas de este holocausto no me fueron develadas, pero no me costó mucho concebirlas, como creo que tampoco les costará a ustedes esfuerzo alguno, el imaginarlas, si observan con detenimiento a su alrededor.', imagen:bomba1, tecla: 'Apreta "A" para continuar', tamanoTexto: 24, posicionXtexto: 70, posicionYtexto: 100, posicionXimagen: 510, posicionYimagen: 1070, escala: 0.70, opacidad:80, anchoTexto: 550},
  {texto: 'Horrorizado, pensé que esta era un relato sobre el fin, pero para mi sorpresa, muchos habían sobrevivido. En las sombras de la civilización, las viejas ideas renacieron, los antiguos mitos, las brillantes utopías y los resplandecientes fantasmas, tiempo atrás olvidados, cobraron vida nuevamente. Las porciones supervivientes de la Humanidad empezaron a organizarse de manera colectivista. De las cenizas surgió una civilización basada en la noción del gasto.', imagen:estatua1, tecla: 'Apreta "A" para continuar', tamanoTexto:24, posicionXtexto: 105, posicionYtexto: 100, posicionXimagen: 510, posicionYimagen: 1030, escala: 0.70, opacidad:40, anchoTexto: 500},
   {texto: 'No había producción ni acumulación en el sentido que nosotros lo entendemos hoy. Estos humanos vivían bajo el principio de la dilapidación y del intercambio simbólico, no existía la idea del trabajo. Concebían que el bien último estaba en llegar al límite y siempre poner en juego al propio ser. Esta humanidad brillaba, entre la abundancia y el juego de los escombros, por su temeridad suicida y su éxtasis orgiástico.', imagen:humano2, tecla: 'Apreta "A" para continuar', tamanoTexto:24, posicionXtexto: 95, posicionYtexto: 100, posicionXimagen: 510, posicionYimagen: 1000, escala: 0.70, opacidad:80, anchoTexto: 500},
  {texto: 'Sin embargo, estos seres libres, a nuestros ojos post-morales, no se encontraban solos. Algunos fragmentos del Capital habían sobrevivido a la autodestrucción en la forma de trabajo muerto independizado y en una clase dominante que había resistido el holocausto exiliando sus consciencias a las profundidades subterráneas de la Red. Una nueva batalla, contra el capital fijo automatizado aliado con los restos virtuales de la ceocracia de la pre-guerra, comenzó inmediatamente.', imagen:soldado, tecla: 'Apreta "A" para continuar', tamanoTexto:24, posicionXtexto: 80, posicionYtexto: 100, posicionXimagen: 510, posicionYimagen: 1000, escala: 0.70, opacidad:40, anchoTexto: 550},
  {texto: 'Los Humanos lucharon valientemente entre los cadáveres aplanados de las aniquiladas megalópolis del mundo. A pesar de su entrega, la victoria se encontraba muy lejos. Esta vez, parecía que la extinción estaba más cerca que nunca y que el virus del Tecnocapital iba a engullirse finalmente a la Gaia Extática en un último bostezo.', imagen:stalingrado, tecla: 'Apreta "A" para continuar', tamanoTexto:24, posicionXtexto: 100, posicionYtexto: 130, posicionXimagen: 510, posicionYimagen: 950, escala: 0.70, opacidad:60, anchoTexto: 500},
  {texto: 'Aunque la historia del Homo Sapiens parecía estar por acabar, en una conjunción aparentemente fortuita, a esta especie en vilo se le reveló la clave de la victoria. Bajo la superficie de los mares y océanos del planeta, los delfines habían vivido durante milenios en una cultura y civilización que prescindía de los objetos materiales. Nunca habían concebido los peligros del dinero ni del fetichismo mercantil. Su vida era puro Don. A pesar de esta vida excelsa, a nuestros ojos contemporáneos, el holocausto humano fue tal que ninguna especie del planeta quedo exenta de sus efectos cataclísmicos.', imagen:humano3, tecla: 'Apreta "A" para continuar', tamanoTexto:24, posicionXtexto: 45, posicionYtexto: 100, posicionXimagen: 510, posicionYimagen: 1030, escala: 0.70, opacidad:80, anchoTexto: 620},
  {texto: 'Ante la situación de emergencia, los cetáceos, organizados en asambleas oceánicas, determinaron que para triunfar en su lucha por la existencia era imperioso el contactar con los terrestres y ayudarlos en su lucha contra el Capital. En un magnánimo acto de solidaridad interespecie, develaron a la Humanidad, mediante proyecciones astrales, los secretos del Tono de los Mares. Fue así que, por primera vez en la historia natural de los mamíferos, las dos especies inteligentes del planeta pudieron hablar y cantar en la misma lengua.', imagen:delfin2, tecla: 'Apreta "A" para continuar', tamanoTexto:24, posicionXtexto: 45, posicionYtexto: 100, posicionXimagen: 510, posicionYimagen: 985, escala: 0.70, opacidad:40, anchoTexto: 620},
   {texto: 'A partir de este punto la reconstrucción de mi visión se me hace casi imposible. De algún modo, al establecer comunicación entre ellas, la Palabra misma, como un virus, se propagó y unificó a las dos especies en una conciencia global. No esta ya en mí poder comprender lo que habían alcanzado aquellas inteligencias y narrárselo a ustedes. Sin embargo, puedo decirles que esa forma de conciencia colectiva, no implicaba una pérdida de la individualidad, sino que ambos tipos de conciencia coexistían sin contradecirse.', imagen:buda, tecla: 'Apreta "A" para continuar', tamanoTexto:24, posicionXtexto: 45, posicionYtexto: 100, posicionXimagen: 510, posicionYimagen: 950, escala: 0.70, opacidad:40, anchoTexto: 600},
   {texto: 'Las percepciones y pensamientos individuales estaban disponibles para la totalidad de los miembros de las dos especies, y ambas humanidades podían tomar decisiones como un todo unificado. Sin embargo, cada ser, a pesar de ese tráfico infinito de sensibilidades e intensidades, seguía en posesión de una singularidad que lo diferenciaba del resto. Esta conciencia planetaria, propagándose a través del mismísimo campo magnético y llegando al centro telúrico incandescente de la Tierra, absorbió y neutralizó al Capital, tal como un anticuerpo actuá contra un virus.', imagen:planeta2, tecla: 'Apreta "A" para continuar', tamanoTexto:24, posicionXtexto: 50, posicionYtexto: 100, posicionXimagen: 510, posicionYimagen: 1030, escala: 0.70, opacidad:40, anchoTexto: 600},
  {texto: 'Fue luego de esta visión que la ví a ELLA', imagen:estatua1, tamanoTexto:25, posicionXtexto: 100, posicionYtexto:500, posicionXimagen: 1, posicionYimagen: 1,  tecla: '', escala: 0, opacidad:40, anchoTexto: 500},
  {texto: 'Soy Vuestra Señora del Futuro, la que cabalga sobre los ardientes vientos del Sahel', imagen:NSDF1opaca1, tamanoTexto:22, posicionXtexto: 80, posicionYtexto:1080, posicionXimagen: 540, posicionYimagen: 1050,  tecla: '', escala: 0.65, opacidad:40, anchoTexto: 550},
  {texto: 'Debes predicar este mensaje para que todos los seres de tu planeta atiendan a la Llamada', imagen:NSDF1opaca1, tamanoTexto:22, posicionXtexto: 80, posicionYtexto:1080, posicionXimagen: 540, posicionYimagen: 1050,  tecla: '', escala: 0.65, opacidad:40, anchoTexto: 550},
  {texto: '¿Aceptas dedicar tu vida a esta Visión que te he regalado?', imagen:NSDF1opaca1, tamanoTexto:22, posicionXtexto: 130, posicionYtexto:1080, posicionXimagen: 540, posicionYimagen: 1050,  tecla: '', escala: 0.65, opacidad:40, anchoTexto: 450},
   ];
  
}

